/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package laboratorioevaluado1.View;

/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        PanelVertical1 = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        PanelHorizontal1 = new javax.swing.JPanel();

        jScrollPane2.setViewportView(jDateChooser1);

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelVertical1.setBackground(new java.awt.Color(51, 51, 51));
        PanelVertical1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMenu.setText("Menu");
        PanelVertical1.add(jLabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorioevaluado1/View/resources/images/logo.png"))); // NOI18N
        PanelVertical1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 190));

        btnInicio.setText("Inicio");
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciobotonInicio(evt);
            }
        });
        PanelVertical1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));
        PanelVertical1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, -1));

        add(PanelVertical1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 520));

        PanelHorizontal1.setBackground(new java.awt.Color(164, 159, 224));
        PanelHorizontal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(PanelHorizontal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciobotonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciobotonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciobotonInicio

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicioMouseClicked

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHorizontal1;
    private javax.swing.JPanel PanelVertical1;
    public javax.swing.JButton btnInicio;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

}
