/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorioevaluado1.View;

/**
 *
 * @author jrmat
 */
public class PantallaInicio extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio
     */
    public PantallaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVertical2 = new javax.swing.JPanel();
        btnComprarMedicamento = new javax.swing.JButton();
        jLabelMenu1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnInicio3 = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnVencimiento = new javax.swing.JButton();
        btnColocarOferta = new javax.swing.JButton();
        btnRetirarOferta1 = new javax.swing.JButton();
        btnRetirarOferta2 = new javax.swing.JButton();
        btnComprarMedicamento1 = new javax.swing.JButton();
        PanelHorizontal2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelVertical2.setBackground(new java.awt.Color(51, 51, 51));
        PanelVertical2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComprarMedicamento.setText("Ver inventario");
        btnComprarMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnComprarMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprarMedicamentoMouseClicked(evt);
            }
        });
        btnComprarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarMedicamentobotonInicio(evt);
            }
        });
        PanelVertical2.add(btnComprarMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, -1));

        jLabelMenu1.setText("Menu");
        PanelVertical2.add(jLabelMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laboratorioevaluado1/View/resources/images/logo.png"))); // NOI18N
        PanelVertical2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 190));

        btnAgregar.setText("Agregar");
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarbotonInicio(evt);
            }
        });
        PanelVertical2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 170, -1));

        btnModificar.setText("Modificar");
        btnModificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarbotonInicio(evt);
            }
        });
        PanelVertical2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, -1));

        btnInicio3.setText("Eliminar");
        btnInicio3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicio3MouseClicked(evt);
            }
        });
        btnInicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicio3botonInicio(evt);
            }
        });
        PanelVertical2.add(btnInicio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 170, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarMouseClicked(evt);
            }
        });
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarbotonInicio(evt);
            }
        });
        PanelVertical2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 170, -1));

        btnVencimiento.setText("Verificar vencimiento");
        btnVencimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVencimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVencimientoMouseClicked(evt);
            }
        });
        btnVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVencimientobotonInicio(evt);
            }
        });
        PanelVertical2.add(btnVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, -1));

        btnColocarOferta.setText("Colocar oferta");
        btnColocarOferta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnColocarOferta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColocarOfertaMouseClicked(evt);
            }
        });
        btnColocarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColocarOfertabotonInicio(evt);
            }
        });
        PanelVertical2.add(btnColocarOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, -1));

        btnRetirarOferta1.setText("Retirar oferta");
        btnRetirarOferta1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRetirarOferta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarOferta1MouseClicked(evt);
            }
        });
        btnRetirarOferta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarOferta1botonInicio(evt);
            }
        });
        PanelVertical2.add(btnRetirarOferta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, -1));

        btnRetirarOferta2.setText("Ver costos");
        btnRetirarOferta2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRetirarOferta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarOferta2MouseClicked(evt);
            }
        });
        btnRetirarOferta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarOferta2botonInicio(evt);
            }
        });
        PanelVertical2.add(btnRetirarOferta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, -1));

        btnComprarMedicamento1.setText("Comprar");
        btnComprarMedicamento1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnComprarMedicamento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComprarMedicamento1MouseClicked(evt);
            }
        });
        btnComprarMedicamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarMedicamento1botonInicio(evt);
            }
        });
        PanelVertical2.add(btnComprarMedicamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, -1));

        getContentPane().add(PanelVertical2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 170, 520));

        PanelHorizontal2.setBackground(new java.awt.Color(164, 159, 224));
        PanelHorizontal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanelHorizontal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMedicamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarMedicamentoMouseClicked

    private void btnComprarMedicamentobotonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarMedicamentobotonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarMedicamentobotonInicio

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnAgregarbotonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarbotonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarbotonInicio

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarbotonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarbotonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarbotonInicio

    private void btnInicio3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicio3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicio3MouseClicked

    private void btnInicio3botonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicio3botonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInicio3botonInicio

    private void btnConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarMouseClicked

    private void btnConsultarbotonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarbotonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarbotonInicio

    private void btnVencimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVencimientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVencimientoMouseClicked

    private void btnVencimientobotonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVencimientobotonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVencimientobotonInicio

    private void btnColocarOfertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColocarOfertaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnColocarOfertaMouseClicked

    private void btnColocarOfertabotonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColocarOfertabotonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnColocarOfertabotonInicio

    private void btnRetirarOferta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarOferta1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarOferta1MouseClicked

    private void btnRetirarOferta1botonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarOferta1botonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarOferta1botonInicio

    private void btnRetirarOferta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarOferta2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarOferta2MouseClicked

    private void btnRetirarOferta2botonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarOferta2botonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarOferta2botonInicio

    private void btnComprarMedicamento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMedicamento1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarMedicamento1MouseClicked

    private void btnComprarMedicamento1botonInicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarMedicamento1botonInicio
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarMedicamento1botonInicio

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHorizontal2;
    private javax.swing.JPanel PanelVertical2;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnColocarOferta;
    public javax.swing.JButton btnComprarMedicamento;
    public javax.swing.JButton btnComprarMedicamento1;
    public javax.swing.JButton btnConsultar;
    public javax.swing.JButton btnInicio3;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnRetirarOferta1;
    public javax.swing.JButton btnRetirarOferta2;
    public javax.swing.JButton btnVencimiento;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMenu1;
    // End of variables declaration//GEN-END:variables
}
